"""Generate the project index from reviewed metadata, using only the standard library."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path, PurePosixPath
import re
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = Path("docs/project-index.md")
FIELDS = ("id", "name", "repository", "focus", "status", "case_study")


def load_projects(root: Path) -> list[dict[str, str]]:
    root = root.resolve()
    data = json.loads((root / "projects.json").read_text(encoding="utf-8"))
    if data.get("schema_version") != 1 or not isinstance(data.get("projects"), list):
        raise ValueError("Expected schema_version 1 and a projects list")
    if not data["projects"]:
        raise ValueError("The project catalog is empty")
    seen = set()
    for project in data["projects"]:
        if not isinstance(project, dict) or any(
            not isinstance(project.get(field), str) or not project[field].strip()
            for field in FIELDS
        ):
            raise ValueError("Each project needs nonempty text fields: " + ", ".join(FIELDS))
        identifier = project["id"]
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", identifier) or identifier in seen:
            raise ValueError(f"Invalid or duplicate project id: {identifier}")
        seen.add(identifier)
        url = urlsplit(project["repository"])
        if (url.scheme != "https" or url.netloc != "github.com" or url.query or url.fragment
                or not re.fullmatch(r"/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", url.path)):
            raise ValueError(f"Project {identifier} needs a canonical HTTPS GitHub repository URL")
        case = PurePosixPath(project["case_study"])
        if (case.is_absolute() or ".." in case.parts or "\\" in str(case)
                or len(case.parts) < 2 or case.parts[0] != "docs" or case.suffix != ".md"):
            raise ValueError(f"Project {identifier} case study must be a Markdown file in docs/")
        resolved = (root / str(case)).resolve()
        if not resolved.is_relative_to(root / "docs") or not resolved.is_file():
            raise ValueError(f"Missing or unsafe case study for {identifier}")
    return data["projects"]


def cell(value: str) -> str:
    # Literal text must not inject HTML, Markdown links, or extra table rows.
    value = html.escape(" ".join(value.split()), quote=False)
    for character in ("\\", "[", "]", "*", "_", "`", "|"):
        value = value.replace(character, "\\" + character)
    return value


def render_catalog(projects: list[dict[str, str]]) -> str:
    lines = [
        "<!-- Generated by scripts/render_catalog.py. Edit projects.json, then regenerate. -->",
        "# Project index", "",
        "Each entry links to source code and a write-up that explains the implementation scope.",
        "Prototypes and learning exercises are identified explicitly.", "",
        "| Project | Focus | Scope | Read more |",
        "|---|---|---|---|",
    ]
    for project in projects:
        case = PurePosixPath(project["case_study"]).relative_to("docs").as_posix()
        lines.append(
            f"| [{cell(project['name'])}]({project['repository']}) | {cell(project['focus'])} "
            f"| {cell(project['status'])} | [Write-up]({case}) |"
        )
    lines.extend(["", "Source metadata: [projects.json](../projects.json).", "",
                  "[Back to profile](../README.md)", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the generated index is stale")
    args = parser.parse_args()
    try:
        content = render_catalog(load_projects(ROOT))
        destination = ROOT / OUTPUT
        if args.check:
            if not destination.is_file() or destination.read_text(encoding="utf-8") != content:
                print("Project index is stale. Run: python scripts/render_catalog.py")
                return 1
            print("Project catalog is valid and the generated index is current.")
        else:
            destination.write_text(content, encoding="utf-8", newline="\n")
            print(f"Updated {OUTPUT.as_posix()}")
        return 0
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"Catalog error: {error}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
